services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883" # MQTT
      - "8883:8883" # MQTTS (secure)
      - "9001:9001" # WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    environment:
      - TZ=UTC
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mosquitto_sub -h localhost -t 'healthcheck' -C 1 || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s # Initial delay before starting health checks
    networks:
      - mqtt_network

  mqtt-publisher:
    build: ./python-app/publisher # Path to your Python application's Dockerfile
    container_name: mqtt_publisher
    depends_on:
      - mqtt-broker # Ensures broker starts before the app
    environment:
      MQTT_BROKER_HOST: mqtt-broker # Use the service name as hostname
      MQTT_BROKER_PORT: 1883
    networks:
      - mqtt_network

  mqtt-subscriber:
    build: ./python-app/subscriber # Path to your Python application's Dockerfile
    container_name: mqtt_subscriber
    depends_on:
      - mqtt-broker # Ensures broker starts before the app
    environment:
      MQTT_BROKER_HOST: mqtt-broker # Use the service name as hostname
      MQTT_BROKER_PORT: 1883
    networks:
      - mqtt_network

  mysql-db:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # Replace with a strong password
      MYSQL_DATABASE: mqtt_db # Replace with your desired database name
      MYSQL_USER: raphaelzh # Replace with your desired username
      MYSQL_PASSWORD: 123456 # Replace with a strong password
    ports:
      # - "3306:3306" # Standard MySQL port
      - "13306:3306" # Standard MySQL port
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: unless-stopped
    depends_on:
      - mqtt-broker # Optional: Ensure MQTT starts first if your application relies on it
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge

volumes:
  mosquitto_data:
    driver: local
  mosquitto_config:
    driver: local
  mosquitto_log:
    driver: local
  mysql_data:
    driver: local